"""Config generators that merge base templates with project exceptions."""

from __future__ import annotations


def make_header(comment_prefix: str = "#", extra_lines: tuple[str, ...] = ()) -> str:
    """Generate the standard AUTO-GENERATED header for config files.

    Args:
        comment_prefix: Comment syntax for the target format (e.g. "#", "//").
        extra_lines: Additional description lines appended after the main header,
            wrapped in their own separator.

    Returns:
        Header string ending with a newline.

    """
    p = comment_prefix
    sep = f"{p} " + "=" * 77
    edit_msg = "Do not edit this file directly."
    rerun_msg = "Edit .guardrails-exceptions.toml and re-run:"
    lines = [
        sep,
        f"{p} AUTO-GENERATED by ai-guardrails-generate",
        f"{p} Source: .guardrails-exceptions.toml",
        f"{p} {edit_msg} {rerun_msg}",
        f"{p}   ai-guardrails-generate",
        sep,
    ]
    lines.extend(f"{p} {line}" if line else p for line in extra_lines)
    if extra_lines:
        lines.append(sep)
    return "\n".join(lines) + "\n"
