"""Shared utilities for hook modules."""

from __future__ import annotations

from pathlib import Path

_HEADER_SCAN_LINES = 5


def has_autogenerated_header(filepath: str) -> bool:
    """Check if a file contains an AUTO-GENERATED marker in its first few lines.

    Args:
        filepath: Path to the file to check.

    Returns:
        True if the file contains "AUTO-GENERATED" in the first 5 lines.

    """
    try:
        with Path(filepath).open() as f:
            for _ in range(_HEADER_SCAN_LINES):
                line = f.readline()
                if not line:
                    break
                if "AUTO-GENERATED" in line:
                    return True
    except OSError:
        pass
    return False
