"""Claude Code PreToolUse hook: protect generated and config files.

Prompts user approval before:
1. Editing auto-generated config files
2. Editing .guardrails-exceptions.toml
3. Adding ignore patterns to config files

Replaces lib/hooks/protect-generated-configs.sh.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from guardrails.constants import (
    CONFIG_FILES,
    GENERATED_CONFIGS,
    IGNORE_PATTERN,
    REGISTRY_FILENAME,
)
from guardrails.hooks._utils import has_autogenerated_header


def _emit_ask(reason: str) -> int:
    output = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "ask",
            "permissionDecisionReason": reason,
        }
    }
    print(json.dumps(output))
    return 0


def main() -> int:  # noqa: PLR0911
    """Entry point. Reads JSON from stdin, emits decision to stdout."""
    # Bail out if no guardrails project
    if not Path(REGISTRY_FILENAME).is_file():
        return 0

    # Read JSON from stdin
    try:
        raw = sys.stdin.read()
        data = json.loads(raw)
    except (json.JSONDecodeError, OSError):
        return 0

    # Extract file_path from tool_input
    tool_input = data.get("tool_input", {})
    file_path = tool_input.get("file_path", "")
    if not file_path:
        return 0

    basename = Path(file_path).name

    # Check 1: Auto-generated config files
    if (
        basename in GENERATED_CONFIGS
        and Path(file_path).is_file()
        and has_autogenerated_header(file_path)
    ):
        return _emit_ask(
            "This file is auto-generated from "
            ".guardrails-exceptions.toml "
            "by ai-guardrails-generate. Direct edits will be "
            "overwritten on next run. Edit "
            ".guardrails-exceptions.toml instead, then run "
            "ai-guardrails-generate. Explain why editing "
            "directly is the only solution."
        )

    # Check 2: .guardrails-exceptions.toml itself
    if basename == REGISTRY_FILENAME:
        return _emit_ask(
            "This is the single source of truth for all lint "
            "exceptions in this project. Every change MUST have "
            "a documented reason. Explain why this exception is "
            "necessary and cannot be fixed in the code."
        )

    # Check 3: Ignore patterns in config files
    if basename in CONFIG_FILES:
        new_content = tool_input.get("new_string") or tool_input.get("content") or ""
        if new_content and re.search(IGNORE_PATTERN, new_content, re.IGNORECASE):
            return _emit_ask(
                f"Ignore pattern detected in {basename}. Lint "
                "exceptions must go in "
                ".guardrails-exceptions.toml, not directly in "
                "config files. Run ai-guardrails-generate to "
                "apply changes. Explain why this is the only "
                "solution."
            )

    # Allow silently
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
