# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

language: en-US

reviews:
  # Assertive = thorough, detailed feedback (matches our pedantic philosophy)
  profile: "assertive"

  # Submit "Request Changes" when actionable comments exist
  # Submit "Approved" when all comments are resolved
  request_changes_workflow: true

  # Review output
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # Auto-review disabled — trigger on-demand via /review-all
  auto_review:
    enabled: false
    drafts: false
    auto_incremental_review: true

  # Stop review if PR is closed/merged
  abort_on_close: true

  # Path-specific review instructions
  path_instructions:
    - path: "**/*.py"
      instructions: |
        - Enforce type hints on all function signatures
        - Check for proper exception handling (no bare except)
        - Verify docstrings on public functions/classes
    - path: "**/*.sh"
      instructions: |
        - Verify scripts use set -euo pipefail
        - Check for proper quoting of variables
        - Ensure portable syntax (POSIX where possible, or document bash-isms)
    - path: "**/tests/**"
      instructions: |
        - Focus on test coverage and edge cases
        - Verify meaningful assertions

  # Static analysis tools — all enabled for maximum coverage
  tools:
    # Python
    ruff:
      enabled: true
    # Shell
    shellcheck:
      enabled: true
    # Markdown
    markdownlint:
      enabled: true
    # YAML
    yamllint:
      enabled: true
    # Security — secret detection
    gitleaks:
      enabled: true
    # Security — SAST
    semgrep:
      enabled: true
    # Security — dependency vulnerabilities
    osv-scanner:
      enabled: true
    # Security — IaC scanning
    checkov:
      enabled: true
    # Spell/grammar checking
    languagetool:
      enabled: true
    # GitHub Actions workflow validation
    actionlint:
      enabled: true
    # Dockerfile best practices
    hadolint:
      enabled: true

  # AI-generated additions
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

chat:
  auto_reply: true
