"""Tests for guardrails.hooks._utils -- shared hook utilities."""

from __future__ import annotations

from pathlib import Path

from guardrails.hooks._utils import has_autogenerated_header


class TestHasAutogeneratedHeader:
    """Test AUTO-GENERATED header detection in first 5 lines."""

    def test_returns_true_when_marker_in_first_line(self, tmp_path: Path) -> None:
        f = tmp_path / "config.toml"
        f.write_text("# AUTO-GENERATED by ai-guardrails\nkey = value\n")
        assert has_autogenerated_header(str(f)) is True

    def test_returns_true_when_marker_on_line_5(self, tmp_path: Path) -> None:
        lines = ["line1\n", "line2\n", "line3\n", "line4\n", "# AUTO-GENERATED\n"]
        f = tmp_path / "config.toml"
        f.write_text("".join(lines))
        assert has_autogenerated_header(str(f)) is True

    def test_returns_false_when_marker_on_line_6(self, tmp_path: Path) -> None:
        lines = [f"line{i}\n" for i in range(5)] + ["# AUTO-GENERATED\n"]
        f = tmp_path / "config.toml"
        f.write_text("".join(lines))
        assert has_autogenerated_header(str(f)) is False

    def test_returns_false_when_no_marker(self, tmp_path: Path) -> None:
        f = tmp_path / "config.toml"
        f.write_text("# Normal header\nkey = value\n")
        assert has_autogenerated_header(str(f)) is False

    def test_returns_false_for_empty_file(self, tmp_path: Path) -> None:
        f = tmp_path / "empty.toml"
        f.write_text("")
        assert has_autogenerated_header(str(f)) is False

    def test_returns_false_for_nonexistent_file(self, tmp_path: Path) -> None:
        assert has_autogenerated_header(str(tmp_path / "missing.toml")) is False

    def test_marker_substring_detection(self, tmp_path: Path) -> None:
        """AUTO-GENERATED can appear anywhere in the line."""
        f = tmp_path / "config.json"
        f.write_text('{"_comment": "AUTO-GENERATED by guardrails"}\n')
        assert has_autogenerated_header(str(f)) is True
