#!/usr/bin/env bats
# =============================================================================
# Tests for protect-generated-configs.sh (Claude Code PreToolUse hook)
# =============================================================================
# Verifies that the hook correctly prompts before edits to:
# 1. Auto-generated config files
# 2. The .guardrails-exceptions.toml registry
# 3. Config files with ignore patterns added
# =============================================================================

load helpers

HOOK_SCRIPT="$REPO_ROOT/lib/hooks/protect-generated-configs.sh"

setup() {
  setup_test_dir
}

teardown() {
  teardown_test_dir
}

# =============================================================================
# Not a guardrails project (no .guardrails-exceptions.toml)
# =============================================================================

@test "exits silently when .guardrails-exceptions.toml does not exist" {
  cd "$TEST_DIR"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "ruff.toml", "content": "whatever"}}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# =============================================================================
# Auto-generated config files
# =============================================================================

@test "prompts ask when editing auto-generated ruff.toml" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  printf '# AUTO-GENERATED by ai-guardrails\n# Do not edit\nline3\nline4\nline5\n' >ruff.toml

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "ruff.toml", "content": "new content"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"permissionDecision"'
  assert_contains "$output" '"ask"'
  assert_contains "$output" "auto-generated"
}

@test "prompts ask when editing auto-generated biome.json" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  # shellcheck disable=SC2016  # $generated is a literal JSON key, not a variable
  printf '{\n  "$generated": "AUTO-GENERATED by ai-guardrails-generate",\n  "linter": {}\n}\n' >biome.json

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Edit", "tool_input": {"file_path": "biome.json", "old_string": "{}", "new_string": "{ }"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"permissionDecision"'
  assert_contains "$output" '"ask"'
}

@test "prompts ask when editing auto-generated .markdownlint.jsonc" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  printf '// AUTO-GENERATED by ai-guardrails\n{}\nline3\nline4\nline5\n' >.markdownlint.jsonc

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": ".markdownlint.jsonc", "content": "new"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "allows editing ruff.toml if NOT auto-generated" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  printf 'line-length = 100\n' >ruff.toml

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "ruff.toml", "content": "line-length = 120"}}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "allows editing ruff.toml if file does not exist" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "ruff.toml", "content": "new file"}}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# =============================================================================
# .guardrails-exceptions.toml edits
# =============================================================================

@test "prompts ask when editing .guardrails-exceptions.toml" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": ".guardrails-exceptions.toml", "content": "new"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
  assert_contains "$output" "single source of truth"
}

# =============================================================================
# Ignore patterns in config files
# =============================================================================

@test "prompts ask when adding noqa to pyproject.toml" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Edit", "tool_input": {"file_path": "pyproject.toml", "old_string": "old", "new_string": "ignore = ['E501']"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
  assert_contains "$output" "Ignore pattern"
}

@test "prompts ask when adding eslint-disable to .eslintrc.json" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": ".eslintrc.json", "content": "eslint-disable some-rule"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "prompts ask when adding per-file-ignores to setup.cfg" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Edit", "tool_input": {"file_path": "setup.cfg", "old_string": "old", "new_string": "per-file-ignores = tests/*:E501"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "prompts ask when adding reportMissing false to pyproject.toml" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Edit", "tool_input": {"file_path": "pyproject.toml", "old_string": "old", "new_string": "reportMissingImports = false"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "prompts ask when adding skip list to tsconfig.json" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "tsconfig.json", "content": "skip = [\"something\"]"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "allows normal edits to pyproject.toml without ignore patterns" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Edit", "tool_input": {"file_path": "pyproject.toml", "old_string": "old", "new_string": "version = '2.0'"}}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# =============================================================================
# Edge cases
# =============================================================================

@test "exits silently on empty input" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "exits silently for unrelated file" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": "src/main.py", "content": "print('hello')"}}
EOF

  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "handles absolute file paths" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"

  run bash "$HOOK_SCRIPT" <<EOF
{"tool_name": "Write", "tool_input": {"file_path": "$TEST_DIR/.guardrails-exceptions.toml", "content": "new"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "prompts for .codespellrc auto-generated file" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  printf '# AUTO-GENERATED by ai-guardrails\n[codespell]\nline3\nline4\nline5\n' >.codespellrc

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": ".codespellrc", "content": "new"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}

@test "prompts for .suppression-allowlist auto-generated file" {
  cd "$TEST_DIR"
  touch ".guardrails-exceptions.toml"
  printf '# AUTO-GENERATED by ai-guardrails\nline2\nline3\nline4\nline5\n' >.suppression-allowlist

  run bash "$HOOK_SCRIPT" <<'EOF'
{"tool_name": "Write", "tool_input": {"file_path": ".suppression-allowlist", "content": "new"}}
EOF

  [ "$status" -eq 0 ]
  assert_contains "$output" '"ask"'
}
