#!/usr/bin/env bats
# =============================================================================
# Tests for detect-config-ignore-edits.sh (pre-commit hook)
# =============================================================================
# Verifies that the hook catches ignore-pattern additions in config files
# at commit time as defense in depth.
# =============================================================================

load helpers

HOOK_SCRIPT="$REPO_ROOT/lib/hooks/detect-config-ignore-edits.sh"

setup() {
  setup_test_dir
  git init --quiet "$TEST_DIR"
  cd "$TEST_DIR" || exit 1
  # Configure git identity for CI environments
  git config user.email "test@test.local"
  git config user.name "Test"
  # Create initial commit so git diff works
  echo "init" >README.md
  git add README.md
  git commit --quiet -m "init"
}

teardown() {
  teardown_test_dir
}

# =============================================================================
# No matching files staged
# =============================================================================

@test "exits 0 when no config files are staged" {
  echo "hello" >src.py
  git add src.py

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 0 ]
}

@test "exits 0 when no files are staged at all" {
  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 0 ]
}

# =============================================================================
# Clean config edits (no ignore patterns)
# =============================================================================

@test "exits 0 when pyproject.toml has no ignore patterns added" {
  cat >pyproject.toml <<'TOML'
[project]
name = "test"
version = "1.0"
TOML
  git add pyproject.toml
  git commit --quiet -m "add pyproject"

  # Modify without ignore patterns
  cat >pyproject.toml <<'TOML'
[project]
name = "test"
version = "2.0"
TOML
  git add pyproject.toml

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 0 ]
}

# =============================================================================
# Detect ignore patterns
# =============================================================================

@test "fails when pyproject.toml adds ignore rule" {
  cat >pyproject.toml <<'TOML'
[project]
name = "test"
TOML
  git add pyproject.toml
  git commit --quiet -m "add pyproject"

  cat >pyproject.toml <<'TOML'
[project]
name = "test"

[tool.ruff.lint]
ignore = ["E501"]
TOML
  git add pyproject.toml

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" "pyproject.toml"
  assert_contains "$output" ".guardrails-exceptions.toml"
}

@test "fails when setup.cfg adds per-file-ignores" {
  echo "[metadata]" >setup.cfg
  git add setup.cfg
  git commit --quiet -m "add setup.cfg"

  cat >setup.cfg <<'CFG'
[metadata]
name = test

[flake8]
per-file-ignores = tests/*:E501
CFG
  git add setup.cfg

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" "setup.cfg"
}

@test "fails when .eslintrc.json adds eslint-disable" {
  echo '{}' >.eslintrc.json
  git add .eslintrc.json
  git commit --quiet -m "add eslint config"

  echo '{"rules": {}, "eslint-disable no-console": true}' >.eslintrc.json
  git add .eslintrc.json

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" ".eslintrc.json"
}

@test "fails when .flake8 adds noqa" {
  echo "[flake8]" >.flake8
  git add .flake8
  git commit --quiet -m "add flake8"

  cat >.flake8 <<'CFG'
[flake8]
noqa = true
CFG
  git add .flake8

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" ".flake8"
}

@test "fails when pyproject.toml adds reportMissing false" {
  echo '[project]' >pyproject.toml
  git add pyproject.toml
  git commit --quiet -m "add pyproject"

  cat >pyproject.toml <<'TOML'
[project]
name = "test"
[tool.pyright]
reportMissingImports = false
TOML
  git add pyproject.toml

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" "pyproject.toml"
}

# =============================================================================
# Skip auto-generated files
# =============================================================================

@test "skips auto-generated config files" {
  printf '# AUTO-GENERATED by ai-guardrails\n[tool.ruff.lint]\n' >pyproject.toml
  git add pyproject.toml
  git commit --quiet -m "add auto-gen pyproject"

  printf '# AUTO-GENERATED by ai-guardrails\n[tool.ruff.lint]\nignore = ["E501"]\n' >pyproject.toml
  git add pyproject.toml

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 0 ]
}

# =============================================================================
# New config files (not just edits)
# =============================================================================

@test "fails when new pyproject.toml is created with ignore patterns" {
  cat >pyproject.toml <<'TOML'
[tool.ruff.lint]
ignore = ["E501"]
TOML
  git add pyproject.toml

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
}

# =============================================================================
# Mixed files
# =============================================================================

@test "reports all violations when multiple files have issues" {
  echo "[metadata]" >setup.cfg
  echo '{}' >.eslintrc.json
  git add setup.cfg .eslintrc.json
  git commit --quiet -m "add configs"

  cat >setup.cfg <<'CFG'
[flake8]
per-file-ignores = tests/*:E501
CFG
  echo '{"rules": {"eslint-disable": true}}' >.eslintrc.json
  git add setup.cfg .eslintrc.json

  run bash "$HOOK_SCRIPT"
  [ "$status" -eq 1 ]
  assert_contains "$output" "setup.cfg"
  assert_contains "$output" ".eslintrc.json"
}
