#!/bin/bash
# ============================================
# guardrails-patterns.sh
# Shared constants for ai-guardrails hooks
#
# Sourced by:
#   - protect-generated-configs.sh (Claude Code PreToolUse)
#   - detect-config-ignore-edits.sh (pre-commit)
# ============================================

# shellcheck disable=SC2034  # Variables are used by sourcing scripts

# Config files known to be generated by ai-guardrails-generate
GENERATED_CONFIGS="ruff.toml biome.json .markdownlint.jsonc .codespellrc .suppression-allowlist"

# Config files where ignore patterns should be flagged (space-separated basenames)
CONFIG_FILES="pyproject.toml setup.cfg .flake8 .eslintrc.json .eslintrc.js .eslintrc.yml tsconfig.json tslint.json"

# Regex for matching config filenames in git diff output
CONFIG_PATTERN='pyproject\.toml$|setup\.cfg$|\.flake8$|\.eslintrc\.(json|js|yml)$|tsconfig\.json$|tslint\.json$'

# Regex matching ignore/suppression patterns in config content
IGNORE_PATTERN='ignore[-_]?words|ignore\s*=|per-file-ignores|reportMissing.*false|eslint-disable|noqa|nolint|pragma.*disable|skip\s*=.*\['
