import type { ResolvedConfig } from "@/config/schema";
import type { CommandRunner } from "@/infra/command-runner";
import type { LintIssue } from "@/models/lint-issue";
import { computeFingerprint } from "@/models/lint-issue";
import type { LinterRunner, RunOptions } from "@/runners/types";

// Codes starting with E or F are errors; everything else is a warning.
const ERROR_PREFIXES = ["E", "F"] as const;

function severityForCode(code: string): "error" | "warning" {
  const prefix = code[0];
  return ERROR_PREFIXES.some((p) => p === prefix) ? "error" : "warning";
}

interface RuffItem {
  code: string;
  filename: string;
  location: { row: number; column: number };
  message: string;
}

function isRuffItem(value: unknown): value is RuffItem {
  if (typeof value !== "object" || value === null) return false;
  const v = value as RuffItem & { location: unknown };
  return (
    typeof v.code === "string" &&
    typeof v.filename === "string" &&
    typeof v.location === "object" &&
    v.location !== null &&
    typeof (v.location as { row: unknown; column: unknown }).row === "number" &&
    typeof (v.location as { row: unknown; column: unknown }).column === "number" &&
    typeof v.message === "string"
  );
}

/**
 * Parse ruff JSON array output into normalized LintIssue[].
 * Returns [] for empty stdout, invalid JSON, or non-array output.
 */
export function parseRuffOutput(stdout: string, _config: ResolvedConfig): LintIssue[] {
  if (!stdout.trim()) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(stdout);
  } catch {
    return [];
  }

  if (!Array.isArray(parsed)) return [];

  const issues: LintIssue[] = [];
  for (const item of parsed) {
    if (!isRuffItem(item)) continue;

    const rule = `ruff/${item.code}`;
    const fingerprint = computeFingerprint({
      rule,
      file: item.filename,
      lineContent: item.message,
      contextBefore: [],
      contextAfter: [],
    });

    issues.push({
      rule,
      linter: "ruff",
      file: item.filename,
      line: item.location.row,
      col: item.location.column,
      message: item.message,
      severity: severityForCode(item.code),
      fingerprint,
    });
  }
  return issues;
}

const RUFF_TOML_TEMPLATE = `\
# ai-guardrails:sha256=<computed>
# Generated by ai-guardrails — do not edit manually
# Regenerate: ai-guardrails generate

target-version = "py311"
line-length = 88
indent-width = 4
fix = false
unsafe-fixes = false

[lint]
select = ["ALL"]

ignore = [
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
  "ANN",
  "D",
  "FIX001",
  "FIX002",
  "TD",
  "ERA001",
  "CPY001",
  "INP001",
  "T201",
  "EM101",
  "EM102",
  "TRY003",
  "S101",
]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "ARG001",
  "ARG002",
  "PLR2004",
]
"**/__init__.py" = [
  "F401",
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-type-checking]
strict = true
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[lint.isort]
force-single-line = false
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = true
force-to-top = ["__future__"]
required-imports = ["from __future__ import annotations"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-tidy-imports.banned-api]
"typing.Optional".msg = "Use \`X | None\` instead"
"typing.Union".msg   = "Use \`X | Y\` instead"
"typing.List".msg    = "Use \`list[X]\` instead"
"typing.Dict".msg    = "Use \`dict[X, Y]\` instead"
"typing.Set".msg     = "Use \`set[X]\` instead"
"typing.Tuple".msg   = "Use \`tuple[X, ...]\` instead"

[lint.mccabe]
max-complexity = 10

[lint.pylint]
max-args = 5
max-bool-expr = 3
max-branches = 10
max-locals = 10
max-nested-blocks = 3
max-positional-args = 5
max-public-methods = 15
max-returns = 4
max-statements = 30

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Path"]

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = true
parametrize-names-type = "csv"
parametrize-values-type = "list"
raises-require-match-for = ["ValueError", "TypeError", "KeyError", "RuntimeError"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 80
`;

export const ruffRunner: LinterRunner = {
  id: "ruff",
  name: "Ruff",
  configFile: "ruff.toml",
  installHint: {
    description: "Python linter and formatter",
    pip: "pip install ruff",
  },

  async isAvailable(runner: CommandRunner): Promise<boolean> {
    const result = await runner.run(["ruff", "--version"]);
    return result.exitCode === 0;
  },

  async run(opts: RunOptions): Promise<LintIssue[]> {
    const { projectDir, config, commandRunner } = opts;
    const result = await commandRunner.run(["ruff", "check", "--output-format=json", projectDir], {
      cwd: projectDir,
    });
    return parseRuffOutput(result.stdout, config);
  },

  generateConfig(_config: ResolvedConfig): string {
    return RUFF_TOML_TEMPLATE;
  },
};
