# AI Guardrails - CI Check Workflow
# Runs pre-commit checks (verify-only, no code modifications)
name: Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install pre-commit
        run: uv tool install pre-commit

      # Skip format-and-stage (local-only) and semgrep (run separately for parallelism)
      - name: Run pre-commit checks
        run: SKIP=format-and-stage,semgrep pre-commit run --all-files

      - name: Run semgrep (parallel)
        run: |
          uv tool install semgrep
          semgrep --config auto --error --exclude tests/

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests with coverage
        run: |
          uv run pytest tests/ \
            --cov \
            --cov-branch \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=85

      - name: Run type checker
        run: uv run pyright
