#!/usr/bin/env bun
// Cross-platform builder for the hk + hk-cc-tools binaries.
//
// hook-kit's `build` CLI compiles for the host only. For releases we need
// linux/darwin × x64/arm64, so we generate the same wrapper shape (mirrors
// hook-kit/src/build/bundle.ts) and invoke `bun build --compile --target=...`.
// Wrapper shape is part of hook-kit's stable public surface — see SPEC.md.
//
// Usage: bun scripts/build-hk-binaries.ts <target> <out-dir>
//   target  : linux-x64 | linux-arm64 | darwin-x64 | darwin-arm64
//   out-dir : output directory

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

function writeErr(msg: string): void {
  process.stderr.write(`${msg}\n`);
}

function writeOut(msg: string): void {
  process.stdout.write(`${msg}\n`);
}

const VALID_TARGETS = [
  "linux-x64",
  "linux-arm64",
  "darwin-x64",
  "darwin-arm64",
] as const;
type Target = (typeof VALID_TARGETS)[number];

const [target, outDir] = process.argv.slice(2);
if (target === undefined || outDir === undefined) {
  writeErr("usage: bun scripts/build-hk-binaries.ts <target> <out-dir>");
  process.exit(1);
}
if (!VALID_TARGETS.includes(target as Target)) {
  writeErr(`invalid target: ${target}. valid: ${VALID_TARGETS.join(", ")}`);
  process.exit(1);
}

const projectRoot = resolve(import.meta.dir, "..");
const entrypoint = join(projectRoot, "src", "hooks.ts");
const absOutDir = resolve(outDir);
mkdirSync(absOutDir, { recursive: true });

interface Variant {
  name: string;
  wrapper: (entry: string) => string;
}

const VARIANTS: readonly Variant[] = [
  {
    name: "ai-guardrails-hk",
    wrapper: (entry) =>
      [
        "// Generated by build-hk-binaries.ts — do not edit",
        'import { runShell } from "@questi0nm4rk/hook-kit/wrapper/hk";',
        `import modules from ${JSON.stringify(entry)};`,
        "",
        "runShell(modules);",
        "",
      ].join("\n"),
  },
  {
    name: "ai-guardrails-hk-cc-tools",
    wrapper: (entry) =>
      [
        "// Generated by build-hk-binaries.ts — do not edit",
        'import { run } from "@questi0nm4rk/hook-kit";',
        'import { claudeCodeAdapter } from "@questi0nm4rk/hook-kit/adapters/claude-code";',
        `import modules from ${JSON.stringify(entry)};`,
        "",
        "run(modules, claudeCodeAdapter);",
        "",
      ].join("\n"),
  },
];

for (const v of VARIANTS) {
  const outFile = join(absOutDir, `${v.name}-${target}`);
  // Wrapper inside the plugin tree so node module resolution finds hook-kit.
  const work = mkdtempSync(join(dirname(entrypoint), ".hk-build-"));
  const wrapperPath = join(work, "entry.ts");
  try {
    writeFileSync(wrapperPath, v.wrapper(entrypoint), "utf8");

    const proc = Bun.spawn(
      [
        "bun",
        "build",
        wrapperPath,
        "--compile",
        "--bytecode",
        "--production",
        `--target=bun-${target}`,
        "--outfile",
        outFile,
      ],
      { cwd: projectRoot, stdout: "inherit", stderr: "inherit" }
    );
    const exitCode = await proc.exited;
    if (exitCode !== 0) {
      writeErr(`build failed for ${v.name} (${target})`);
      process.exit(1);
    }
    writeOut(`built ${outFile}`);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}
